o_saint/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import site_scan

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^o_saint/', include('site_scan.urls', namespace = "o_saint")),
]

site_scan/urls.py
from django.conf.urls import url

from site_scan import views

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^search$', views.search, name = "search"),
	url(r'^history$', views.history, name = "history"),
	url(r'^(?P<scan_id>[0-9]+)/$', views.details, name='details'),
	url(r'^SSL/(?P<scan_id>[0-9]+)/$', views.ssl, name='ssl'),
	url(r'^email_detail/$',views.email_detail, name='email_detail'),
	url(r'^cidr/$',views.cidr, name='cidr')
]

site_scan/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class SiteScan(models.Model):
	Site_Name = models.CharField(max_length=200)
	Scan_Date = models.DateTimeField('date scanned')
	Scan_Completed = models.CharField(max_length=10, default='Running')
	SSL_Grade = models.CharField(max_length=3, default=0)
	SSL_SName = models.CharField(max_length=200, default=0)
	SSL_IP = models.CharField(max_length=16, default=0)
	SSL_Port = models.CharField(max_length=5, default=0)
	SSL_ServSig = models.CharField(max_length=32, default=0)
	SSL_Full = models.CharField(max_length=100, default=0)
	SSL_NIST = models.CharField(max_length=10, default=0)
	SSL_HIPAA = models.CharField(max_length=10, default=0)
	SSL_PCI = models.CharField(max_length=10, default=0)
	WhoIsDomain = models.CharField(max_length=200, default=0)
	WhoIsEmails = models.CharField(max_length=200, default=0)
	WhoIsUpdated = models.DateTimeField('Updated Date', default=timezone.now)
	WhoIsWServer = models.CharField(max_length=200, default=0)
	WhoIsCity = models.CharField(max_length=200, default=0)
	WhoIsExpiration = models.DateTimeField('Expiration Date', default=timezone.now)
	WhoIsNameServer = models.CharField(max_length=200, default=0)
	WhoIsState = models.CharField(max_length=200, default=0)
	WhoIsStatus = models.CharField(max_length=200, default=0)
	WhoIsReferral = models.CharField(max_length=200, default=0)
	WhoIsDNSSec = models.CharField(max_length=200, default=0)
	WhoIsCreation = models.DateTimeField('Creation Date', default=timezone.now)
	WhoIsOrg = models.CharField(max_length=200, default=0)
	WhoIsZip = models.CharField(max_length=200, default=0)
	WhoIsName = models.CharField(max_length=200, default=0)
	WhoIsRegistrar = models.CharField(max_length=200, default=0)
	WhoIsCountry = models.CharField(max_length=200, default=0)
	WhoIsAddress = models.CharField(max_length=200, default=0)
	EmailPattern = models.CharField(max_length=50, default=0)
	EmailsAll = models.CharField(max_length=10000, default=0)
	Traceback = models.CharField(max_length=10000, default=0)
	shodan_results = models.CharField(max_length=1000, default="not searched")
	def __str__(self):
		return self.Site_Name
	def was_scanned_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=7) <= self.pub_date <= now

class Emails(models.Model):
	scan = models.ForeignKey(SiteScan, on_delete=models.CASCADE)
	email = models.CharField(max_length=200, default=0)
	def __str__(self):
		return self.email

class DNS(models.Model):
	scan = models.ForeignKey(SiteScan, on_delete=models.CASCADE)
	record = models.CharField(max_length=10, default=0)
	name = models.CharField(max_length=50, default=0)
	address = models.CharField(max_length=50, default=0)
	def __str__(self):
		return self.name

class shodandata(models.Model):
	scan = models.ForeignKey(SiteScan, on_delete=models.CASCADE)
	IP = models.CharField(max_length=20, default=0)
	hostnames = models.CharField(max_length=100, default=0)
	data = models.CharField(max_length=5000, default=0)
	port = models.CharField(max_length=100, default=0)
	def __str__(self):
		return self.name

class ARIN(models.Model):
	scan = models.ForeignKey(SiteScan, on_delete=models.CASCADE)
	netname = models.CharField(max_length=10, default=0)
	cidr = models.CharField(max_length=50, default=0)
	def __str__(self):
		return self.cidr

class user(models.Model):
	scan = models.ForeignKey(SiteScan, on_delete=models.CASCADE)
	status = models.CharField(max_length=6, default=0)
	email = models.CharField(max_length=100, default=0)
	firstname = models.CharField(max_length=100, default=0)
	lastname = models.CharField(max_length=100, default=0)
	fullname = models.CharField(max_length=200, default=0)
	gender = models.CharField(max_length=20, default='Not Available')
	deducedlocation = models.CharField(max_length=100, default=0)
	digitalfootprint = models.CharField(max_length=500, default='Not Available')
	def __str__(self):
		return self.email

class photo(models.Model):
	email = models.ForeignKey(user, on_delete=models.CASCADE)
	ptype = models.CharField(max_length=100, default=0)
	purl = models.CharField(max_length=100, default=0)
	def __str__(self):
		return self.ptype

class organization(models.Model):
	email = models.ForeignKey(user, on_delete=models.CASCADE)
	title = models.CharField(max_length=100, default=0)
	startDate = models.CharField(max_length=100, default=0)
	name = models.CharField(max_length=100, default=0)
	current = models.CharField(max_length=10, default=0)
	def __str__(self):
		return self.name

class socialp(models.Model):
	email = models.ForeignKey(user, on_delete=models.CASCADE)
	stype = models.CharField(max_length=100, default=0)
	url = models.CharField(max_length=100, default=0)
	following = models.CharField(max_length=10, default=0)
	followers = models.CharField(max_length=10, default=0)
	def __str__(self):
		return self.stype

class links(models.Model):
	email = models.ForeignKey(user, on_delete=models.CASCADE)
	url = models.CharField(max_length=200, default=0)

class builtwith(models.Model):
	scan = models.ForeignKey(SiteScan, on_delete=models.CASCADE)
	domain = models.CharField(max_length=200, default=0)
	subdomain = models.CharField(max_length=200, default=0)
	url = models.CharField(max_length=200, default=0)
	name = models.CharField(max_length=200, default=0)
	tag = models.CharField(max_length=200, default=0)
	description = models.CharField(max_length=1000, default=0)
	def __str__(self):
		return self.domain

site_scan/views.py
from django.shortcuts import render, redirect, get_object_or_404
from site_scan.models import SiteScan, user
from django.utils import timezone
from site_scan.SiteGather import scan_site, fullcontact, fullcontact_new
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
import shlex, subprocess
import sys, os
import re

from django.utils.safestring import mark_safe

import json

def index(request):
	return render(request, 'index.html')

def search(request):
	if request.method == "POST":
		site_to_scan = request.POST.get("site_to_scan", None)
		email = request.POST.get("email", None)
		site_email = request.POST.get("site_email", None)
		cwd = os.getcwd()
		cwd = str(cwd)
		if site_to_scan:
			time = timezone.now()
			tstring=time.strftime('%m/%d/%Y')
			sts = SiteScan(Site_Name=site_to_scan+' '+tstring, Scan_Date=time)
			sts.save()
			id = sts.id
			command = "python3 site_scan/SiteGather.py %s %s %s" % (site_to_scan, id, cwd)
			p = subprocess.Popen(command , shell=True, stdout=subprocess.PIPE)
			scannedsite = get_object_or_404(SiteScan, pk=id)
			
			return redirect('/o_saint/%s/' % id)
		elif email:
			results = fullcontact(email)
			results = re.sub("True", "true", str(results))
			return render(request, 'email.html', {'results': results})
		else:
			return redirect('o_saint:index')
	else:
		return redirect('o_saint:index')

def history(request):
	latest_scan_list = SiteScan.objects.order_by('-Scan_Date')[:20]
	template = loader.get_template('history.html')
	context = {
		'latest_scan_list': latest_scan_list,
	}
	return HttpResponse(template.render(context, request))

def details(request, scan_id):
    scan = get_object_or_404(SiteScan, pk=scan_id)
    return render(request, 'detail.html', {'scan': scan})

def ssl(request, scan_id):
	path = 'site_scan/templates/SSL/'
	complete_path = os.path.join(path, str(scan_id))
	with open(complete_path) as json_data:
		results = json.load(json_data)
	results = re.sub("True", "true", str(results))
	results = re.sub("False", "false", str(results))
	return render(request, 'ssl.html', {'results': results})

def email_quick(request):
	if request.method=='GET':
		email = request.GET.get('email')		
		results = fullcontact(email)
		truth = {'True':'true'}
		results = re.sub("True", "true", str(results))
		return render(request, 'email.html', {'results': results})

def email_detail(request):
	if request.method=='GET':
		email_val = request.GET.get('email')
		id = request.GET.get('id')
		fullcontact_new(email_val, id)
		link = email_val+"_"+str(id)	
		results = get_object_or_404(user, email=link)
		return render(request, 'email_detail.html', {'results': results})

def cidr(request):
	cwd = os.getcwd()
	cwd = str(cwd)
	if request.method=='GET':
		cidr = request.GET.get('cidr_val')
		id = request.GET.get('id')
		command = "python3 site_scan/cidr_bruteforce.py %s %s %s" % (cidr, id, cwd)
		p = subprocess.Popen(command , shell=True, stdout=subprocess.PIPE)
		scan = get_object_or_404(SiteScan, pk=id)
		return redirect('/o_saint/%s/' % id)

def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

site_scan/templates/detail.html
{% autoescape off %}
{% block content %}
<head>
<META HTTP-EQUIV="refresh" CONTENT="5">
</head>
<body>
<h1 align="center" color=blue>{{ scan.Site_Name }}</h1>
{% if scan.Scan_Completed != "Running" and scan.Scan_Completed != "Completed" and scan.Scan_Completed != "Bruteforce" %}
<h2 align="center">Scan {{ scan.Scan_Completed }}</h2>
<h3 align="center">Error: {{ scan.Traceback }}</h3>
<h3 align="center">Any results captured before the failure are below. Please look at terminal running the server for error</h3>

{% elif scan.Scan_Completed == "Running" %}
<h2 align="center">Scan is {{ scan.Scan_Completed }}</h2>
<h3 align="center">If scan shows running longer then 30 minutes then something went wrong</h3>

{% elif scan.Scan_Completed == "Bruteforce" %}
<h2 align="center">CIDR Bruteforce running</h2>
<h3 align="center">Brute force can take a long time depending on size of CIDR</h3>

{% endif %}

<p id="email"></p>
<style type="text/css">
.datagrid table { border-collapse: collapse; text-align: left; width: 100%; } 
.datagrid {font: normal 12px/150% Arial, Helvetica, sans-serif; background: #fff; overflow: hidden; border: 1px solid #006699; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.datagrid table td, .datagrid table th { padding: 3px 10px; }.datagrid table thead th {background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #006699), color-stop(1, #00557F) );background:-moz-linear-gradient( center top, #006699 5%, #00557F 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#006699', endColorstr='#00557F');background-color:#006699; color:#FFFFFF; font-size: 20px; font-weight: bold; border-left: 1px solid #0070A8; } 
.datagrid table thead th:first-child { border: none; }
.datagrid table tbody td { color: #00557F; border-left: 1px solid #E1EEF4;font-size: 15px;font-weight: normal;vertical-align: top }
.datagrid table tbody 
.alt td { background: #E1EEf4; color: #00557F; }
.datagrid table tbody td:first-child { border-left: none; }
.datagrid table tbody tr:last-child td { border-bottom: none; }
.datagrid table tfoot td div { border-top: 1px solid #006699;background: #E1EEf4;}
h1 { color: #CEF0D4; font-family: 'Rouge Script', cursive; font-size: 50px; font-weight: normal; line-height: 48px; margin: 0 0 50px; text-align: center; text-shadow: 1px 1px 2px #082b34; }
h2 { color: #a7e8f8; font-family: 'Julius Sans One', sans-serif; font-size: 22px; font-weight: bold; line-height: 32px; margin: 0 0 24px; text-shadow: 1px 1px 1px #082b34; }
</style>


<center>
<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">WhoIs Information</th></tr></thead>

<tbody>
<tr><td width="30%">Domain Information</td>
<td><b>Domains:</b> {{ scan.WhoIsDomain }}
	</br><b>Name Servers:</b> {{ scan.WhoIsNameServer }}
	</br><b>Whois Server:</b> {{ scan.WhoIsWServer }}
	</br><b>Status:</b> {{ scan.WhoIsStatus }}
	</br><b>DNS Sec:</b> {{ scan.WhoIsDNSSec }}
	</br><b>Org:</b> {{ scan.WhoIsOrg }}
	</br><b>Registrar:</b> {{ scan.WhoIsRegistrar }}
	</br><b>Referral URL:</b> {{ scan.WhoIsReferral }}</td></tr>

<tr class="alt"><td width="30%">Address</td>
<td><b>Name:</b> {{ scan.WhoIsName }}
	</br>{{ scan.WhoIsAddress }}
	</br>{{ scan.WhoIsCity }} {{ scan.WhoIsState }}, {{ scan.WhoIsZip }}
	</br>{{ scan.WhoIsCountry }}</td></tr>

</tbody>
</table>
</div>
</br>

<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">SSL Information </th></tr></thead>

<tbody>
<tr><td width="30%">SSL Hostname</td>
<td>{{ scan.SSL_SName }}</td>
</tr>

<tr class="alt"><td>SSL Grade</td>
<td>{{ scan.SSL_Grade }}</td></tr>

<tr><td>SSL IP</td>
<td>{{ scan.SSL_IP }}</td>
</tr>

<tr class="alt"><td>SSL Port</td>
<td>{{ scan.SSL_Port }}</td></tr>

<tr><td>SSL Server Sig</td>
<td>{{ scan.SSL_ServSig }}</td>
</tr>

<tr class="alt"><td>SSL Compliance</td>
<td><b>PCI:</b> {{ scan.SSL_PCI }}</br>
		<b>HIPAA:</b> {{ scan.SSL_HIPAA }}</br>
		<b>NIST:</b> {{ scan.SSL_NIST }}</br></td></tr>

<tr><td>Full SSL Information</td>
<td><a href="/o_saint/SSL/{{ scan.id }}/">{{ scan }}</td>
</tr>
</tbody>
</table>
</div>
</br>
</br>

<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">Email Information</th></tr></thead>

<tbody>
<tr><td width="30%">Email Pattern</td>
<td>{{ scan.EmailPattern }}</td></tr>

<tr class="alt"><td width="30%">All Emails</td>
<td><ul>
	{% for emails in scan.emails_set.all|dictsort:"email" %}
		<li><a href="../email_detail/?email={{ emails.email }}&id={{ scan.id }}">{{ emails.email }}</li>
	{% endfor %}
    </ul></td></tr>

</tbody>
</table>
</div>
</br>

<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">DNS Information</th></tr></thead>

<tbody>
<tr><td width="30%">SOA Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "SOA" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul></td></tr>

<tr class="alt"><td width="30%">NS Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "NS" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul>
</td></tr>

<tr><td width="30%">MX Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "MX" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul></td></tr>

<tr class="alt"><td width="30%">SRV Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "SRV" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul>
</td></tr>

<tr><td width="30%">A Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "A" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul></td></tr>

<tr class="alt"><td width="30%">CNAME Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "CNAME" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul>
</td></tr>

<tr><td width="30%">TXT Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "TXT" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul></td></tr>

<tr class="alt"><td width="30%">PTR Records</td>
<td><ul>
	{% for dns in scan.dns_set.all|dictsort:"name" %}
		{% if dns.record == "PTR" %}
			<li>{{ dns.name }} {{ dns.address }}</li>
		{% endif %}
	{% endfor %}
</ul></td></tr>

<tr><td width="30%">Found CIDRs</br><font size=1 color="black">Click on one of the CIDRs to perform a brute force of that range along with searching Shodan for that net range. Results will be saved and returned on this page</font></td>
<td><ul>
	{% for arin in scan.arin_set.all|dictsort:"netname" %}
		<li><a href="../cidr/?cidr_val={{ arin.cidr }}&id={{ scan.id }}">{{ arin.netname }} {{ arin.cidr }}</li>
	{% endfor %}
</ul>
</td></tr>

</tbody>
</table>
</div>
</br>

<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">Shodan Information</th></tr></thead>

<tbody>
<tr><td width="30%">Total Results</td>
<td>{{ scan.shodan_results }}</td></tr>

<tr class="alt"><td width="30%">Details</td>
<td>	{% for result in scan.shodandata_set.all %}
		IP: {{ result.IP }}</br>Hostnames: {{ result.hostnames }}</br>Data: {{ result.data }}</br>Port(s): {{ result.port }}</br></br>
	{% endfor %}
</td>
</tr>
</tbody>
</table>
</div>
</br>

<div class="datagrid"><table>
<thead><tr><th>Site</th>
    <th>Type</th>
    <th>Name</th>
    <th>Description</th></tr></thead>

<tbody>
{% for domain in scan.builtwith_set.all|dictsort:"subdomain" %}

  <tr class="{% cycle ' ' 'alt' as rowcolors %}">
    <td>{{ domain.subdomain }}.{{ domain.domain}}</td>
    <td>{{ domain.tag }}</td>
    <td>{{ domain.name }}</td>
    <td>{{ domain.description }}</td>
  </tr>
{% endfor %}

</center>

</body>
{% endblock %}
{% endautoescape %}

site_scan/templates/email.html
{% autoescape off %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"> </script>
</head>
<body>
<pre id="json"></pre>
<script>
var data = {{ results }}

document.getElementById("json").innerHTML = JSON.stringify(data, undefined, 2);
</script>
</body>
</html>
{% endblock %}
{% endautoescape %}

site_scan/templates/email_detail.html
{% autoescape off %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<META HTTP-EQUIV="refresh" CONTENT="15">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"> </script>
</head>
<body>

<h1 align="center" color=blue>{{ results.email }}</h1>
{% if results.status == "0" %}

<h2 align="center">Please wait while scan runs</h2>

{% endif %}

<style type="text/css">
.datagrid table { border-collapse: collapse; text-align: left; width: 100%; } 
.datagrid {font: normal 12px/150% Arial, Helvetica, sans-serif; background: #fff; overflow: hidden; border: 1px solid #006699; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.datagrid table td, .datagrid table th { padding: 3px 10px; }.datagrid table thead th {background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #006699), color-stop(1, #00557F) );background:-moz-linear-gradient( center top, #006699 5%, #00557F 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#006699', endColorstr='#00557F');background-color:#006699; color:#FFFFFF; font-size: 20px; font-weight: bold; border-left: 1px solid #0070A8; } 
.datagrid table thead th:first-child { border: none; }
.datagrid table tbody td { color: #00557F; border-left: 1px solid #E1EEF4;font-size: 15px;font-weight: normal;vertical-align: top }
.datagrid table tbody 
.alt td { background: #E1EEf4; color: #00557F; }
.datagrid table tbody td:first-child { border-left: none; }
.datagrid table tbody tr:last-child td { border-bottom: none; }
.datagrid table tfoot td div { border-top: 1px solid #006699;background: #E1EEf4;}
</style>

<center>
{% if results.fullname != "0" %}
<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">User Information</th></tr></thead>

<tbody>
<tr><td width="30%">Name</td>
<td>{{ results.fullname }}</td></tr>

<tr class="alt"><td width="30%">Gender</td>
<td>{{ results.gender }}</td></tr>

<tr><td width="30%">Organizations</td>
<td>
{% for org in results.organization_set.all %}
{{ org.name }}  {{ org.title }}
</br>Start Date: {{ org.startDate }}
</br>Current: {{ org.current }}
</br></br>
{% endfor %}</td></tr>

<tr class="alt"><td width="30%">Digital Footprint/Interest</td>
<td>{{ results.digitalfootprint }}</td></tr>

<tr><td width="30%">Social Profiles</td>
<td>
{% for profiles in results.socialp_set.all %}
{{ profiles.stype }}</br>
URL: <a href="{{ profiles.url }}">{{ profiles.url }}</a></br>
Following: {{ profiles.following }}
Followers: {{ profiles.followers }}</br></br>
{% endfor %}
</td></tr>

<tr class="alt"><td width="30%">Photos</td>
<td>
	{% for photos in results.photo_set.all %}
	{{ photos.ptype }}</br><img src="{{ photos.purl }}" height="100" width="100"></br></br>
	{% endfor %}
</td></tr>

</tbody>
</table>
</div>

{% else %}
	<h1> No data returned from FullContact </h1>
{% endif %}
</br></br>

<div class="datagrid"><table>
<thead><tr><th colspan="2" align="center">Additional Information</th></tr></thead>

<tbody>
<tr><td>Links Found</td>
<td>{% for url in results.links_set.all %}
	<a href="{{ url.url }}">{{ url.url }}</br></br>
{% endfor %}</td></tr>

</tbody>
</table>
</div>
</br>

</body>
</html>
{% endblock %}
{% endautoescape %}

site_scan/templates/history.html
{% if latest_scan_list %}
    <ul>
    {% for scan in latest_scan_list %}
        <li><a href="/o_saint/{{ scan.id }}/">{{ scan }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

site_scan/templates/index.html
{% block content %}	
	<h1 style="font-size: 400%;" align="center">O-SaINT</h1>
</br>
<center>
<form id="ds-scan-form" method="POST" action="search">
<input name="site_to_scan" id='site-search' placeholder="" type="text"></input>
{% csrf_token %}
<button type="submit" form="ds-scan-form" value="Submit">Scan</button>
</form>
</center>

<h3 align="center">Enter the domain name in the above text box and wait.</h3>
</br>

<center>
<form id="ds-search-form" method="POST" action="search">
<input name="email" id='email' placeholder="" type="text"></input>
{% csrf_token %}
<button type="submit" form="ds-search-form" value="Submit">Search</button>
</form>
</center>
<h3 align="center">Enter the email in the above text box and wait.</h3>

<p align="center"><a href="/o_saint/history">Previous Site Scans</a></p>
{% endblock %}

site_scan/templates/scanning.html
<head>
<META HTTP-EQUIV="refresh" CONTENT="15">
</head>
<h1 align="center">{{ scan.Site_Name }}</h1>
<h2 align="center">Percent completed {{ scan.Scan_Completed }}</h2>

site_scan/templates/ssl.html
{% autoescape off %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"> </script>
</head>
<body>
<pre id="json"></pre>
<script>
var data = {{ results }}

document.getElementById("json").innerHTML = JSON.stringify(data, undefined, 2);
</script>
</body>
</html>
{% endblock %}
{% endautoescape %}